### ISSUE TITLE
Book Catalogue gets stuck searching Google Books

### ISSUE THREAD

**Issue by kblin** [eleybourn/Book-Catalogue#528]
When adding a new book by ISBN, Book Catalogue searches a couple of different sources for more information about the book. As of last week, I seem to get stuck searching for the book on Google Books. The search message is stuck on the screen for 5+ minutes. Cancelling the search takes over one minute as well.
Looking at the relevant code in Book Catalogue, it seems like the URL being queried in that case is http://books.google.com/books/feeds/volumes?q=ISBN:<ISBN>
If I try that request manually, e.g. for http://books.google.com/books/feeds/volumes?q=ISBN:9780061020681 I seem to get more than one record back. Could that be the reason for this issue?

**Comment by Grunthos** [comment]
Fixed in 5.1

**Comment by mendell27** [comment]
I am seeing this issue with 5.1 today.

**Comment by Grunthos** [comment]
The fact it finishes in a minute or so suggests this bug is still fixed (used to not timeout). Are you able to cancel?

**Comment by ladyvader19** [comment]
Both my husband and I are experiencing this issue, where the app seems to get hung up on google books for anout 5 minutes and then finds the book.  We started to experiece this a couple of weeks ago, before that it would come up really quickly.   Has there been a resolution to this issue?

**Comment by erikdutton** [comment]
This issue has just surfaced for me in the last few weeks (since the last release?) - it takes several minutes to search Google Books, but does eventually return a value... however, this makes the add function effectively unusable. I'm running the current version of the app on Android Marshmallow (6.0.1), on a Moto G4.

I tried uninstalling and reinstalling the app, but there was no change. Any assistance will be greatly appreciated!
