### ISSUE TITLE
Incorrectly capitalised french characters

### ISSUE THREAD

**Issue by eleybourn** [eleybourn/Book-Catalogue#655]
Hi,

How are you?

I just found another place where Capital letters should not be found in French.

The reason being why I didn't find it earlier is that I did not use this function before.

After checking "Anthology", inside the tab "Titles of anthology", there shouldn't be any Capital letters except at the top of a sentence.

Furthermore, sane thing for all the other tabs, "Notes" and "Loan"....

I don't think I am forgetting anything now, unless there is or there are any other tabs that I am not aware of.

I am sorry not to have noticed that before.

Sincerely,

Daniel

**Comment by Grunthos** [comment]
So, to be clear, we have:

- "Title" and "Series", (you mentioned "Description" in an earlier email, but it is already not capitalized).
- Anthology Title (but not authors, since I assume names should be capitalized...is that right?)


Notes and Loan should also be fine as they are. If not, can you be specific about the fields that ARE CURRENTLY capitalized, and should not be capitalized?
