### ISSUE TITLE
disaster/book catalog app.

### ISSUE THREAD

**Issue by beckyatsea** [eleybourn/Book-Catalogue#665]
Broken phone. I can plug it into the computer but I don't know how to export to the new phone.  I exported a backup to my computer a couple of months ago.  Is there anything I can do to save my book collection?   Thanks.

**Comment by Grunthos** [comment]
If the .bcbk atchive file is sufficiently recent (not many books added/editied 
since it was created), then copy it to the 'bookCatalogue' directory on your new 
phone and run 'Import from Archive'.

If it is not recent enough, did you create a CSV export recently? If not, then 
data since that time is lost unless the phone is usable.

**Comment by beckyatsea** [comment]
Thanks so much. I had almost 1200 books loaded.
