### ISSUE TITLE
Sync with Goodreads Notes

### ISSUE THREAD

**Issue by Glanzer-modder** [eleybourn/Book-Catalogue#812]
I love this app. I can finally keep notes about the books I'm reading or on my to-read list. But I see that the Notes in Book Catalogue are not synced with Goodreads Notes. That would be a big plus.

**Comment by Grunthos** [comment]
This is an interesting one; we originally did sync the notes...but several people (myself included) tended to make more personal comments about books, eg, "Gift from Bob". Or write colourful reviews as personal notes.

I am not entirely sure how to proceed with this. It might be woth having a separate option of "Submit Notes as Review", or something like that.

Any thoughts?

**Comment by Grunthos** [comment]
Or maybe just add a "Review" field and rename the Notes field as "Private Notes". Any thoughts?

**Comment by VariableReferee** [comment]
I agree that the Notes area should be private, i.e. don't link them to the Comments/Reviews in Goodreads. I use Notes for my personal reference, e.g. "This book was suggested by such-n-such podcast on 9/1/2019," or something like that. So renaming it to Private Notes and syncing it with the Notes in Goodreads would be good. **The Notes in Goodreads is private too.** Unfortunately that field in Goodreads can only be seen on a PC; it's not exposed in the Goodreads mobile app. That's one of the reasons I found your app because it allows Notes. BTW, don't confuse the private Goodreads Notes field with the Comments (Review) field--they're separate things.

**Comment by Grunthos** [comment]
Goodreads have disabled all API access so related features are no longer possible
