### ISSUE TITLE
ISBN Scanner

### ISSUE THREAD

**Issue by Bah5127** [eleybourn/Book-Catalogue#863]
I love this app and have used it for years, but ever since I upgraded to the new galaxy s20 I keep getting an error and it won't let me scan books.  
![Screenshot_20200907-114557_Knox Enrollment Service](https://user-images.githubusercontent.com/70907708/92403774-2b7b0d00-f100-11ea-99f8-ca76e594c21b.jpg)

I tried to turn my phone off and it hasn't done anything.

**Comment by icarius22** [comment]
I had a similar problem when changing my cell phone. The problem was that the scanning app was not downloaded. Once I downloaded Barcode Scanner everything worked normally.

**Comment by sixshot** [comment]
I just recently got this issue. I think there needs to be a prompt or a note put somewhere to let people know that isbn barcode scanning requires this app. Also wish there's a working alternative to 'Barcode Scanner' since there are permissions I have to deny. It still works with those denied permissions but would like to know if there's a working modern alternative.

**Comment by Grunthos** [comment]
See our FAQ re scanning issues, but also note that the next release (currently in beta) has a builtin scanner.
