### ISSUE TITLE
backup not working - says no space

### ISSUE THREAD

**Issue by tarrynz** [eleybourn/Book-Catalogue#867]
Hi, I have not been able to create a backup of my library for several months. It tells me there is no space, but there is 4gb free, on my sd card. I have a nokia 7.1 running android 10. I cannot change the backup path either.
Please help, as I can't lose my database! 
I can export to csv.

**Comment by ttamttam** [comment]
Same here. But since today only, after an OS upgrade (lineage 17.1 = android 10)

**Comment by Grunthos** [comment]
Minimal suggestion until the cause is found: export to CSV (that saves the data but not the cover imagess).

Please go to "Backup to Archive" and select a location on the SD card with 4.5gb free, then start the backup. If/when it fails, go to "Help"->"Send Information" and send us the resulting message.

**Comment by ttamttam** [comment]
Since you replied so fast to my comment, here are some more information (maybe not relevant for the original poster, thought?):

> … (that saves the data but not the cover imagess) …
Side note: I also "lost" all the cover images during this OS upgrade… (see below)

 Some tries:

- admin -> Import/Export data -> backup:
   
  I can’t edit the backup location. The default one is "/storage/emulated/0/bookCatalogue".
  I can not navigate to select another backup location either: "No parent directory available".
  With an android terminal emulator, I can `cd` into this directory, but I do not have the permission de `ls` it…
  But I can access the `bookCatalogue` directory from my computer through an USB connection. And can access former backups and cover images.
  
  I'll investigate this before coming back here.

- admin -> Import/Export data -> Export CSV:
  Is failing (certainly because of the very same denied access right). 

Best regards

**Comment by Grunthos** [comment]
Can you go to "Help"->"Send Information" so we can check versions etc. not being able to export the CSV file suggests that BC has no access to the SD Card, which later versions should have requested.

**Comment by ttamttam** [comment]
> Can you go to "Help"->"Send Information" so we can check versions etc. not being able to export the CSV file suggests that BC has no access to the SD Card, which later versions should have requested.

I can’t (yet). Precisely because this would need a write access to the SD card…

**Comment by Grunthos** [comment]
OK, that;s odd. Can you go to Help->About and check the version?

**Comment by ttamttam** [comment]
Sure: I have `5.3.0-4-distplay`.

But I think my problems are not due to BC.
I first have to check that before having you lose your time.

Anyway. Thanks for your interest!

**Comment by ttamttam** [comment]
Summary of my problem again, because I can’t understand it:

- mainly, BC can’t access SD card files (Read or Write):
  - no cover displayed
  - can’t do "help -> send information"
  - but the database itself is read correctly
  - can’t replace the cover of a book with one file from the "Gallery"
- books covers are on the file system (I can see them with a file manager)
- I’m using an android 10 (sdk 29), with SD card mounted as internal storage

Using `adb logcat`, I could capture the following trace, corresponding to the "Help -> send information" failing action:
``` 
...
04-03 14:59:46.534 18021 18021 E BC Logger: An Exception Occured @ 2021-04-03 14:59:46
04-03 14:59:46.534 18021 18021 E BC Logger: In Phone GT-I9505 (29) 
04-03 14:59:46.534 18021 18021 E BC Logger: 
04-03 14:59:46.534 18021 18021 E BC Logger: java.io.FileNotFoundException: /storage/emulated/0/bookCatalogue/bookCataloguebookCatalogueDbExport-tmp.db: open failed: EACCES (Permission denied)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at libcore.io.IoBridge.open(IoBridge.java:496)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at com.eleybourn.bookcatalogue.utils.StorageUtils.backupDbFile(StorageUtils.java:114)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at com.eleybourn.bookcatalogue.CatalogueDBAdapter.backupDbFile(CatalogueDBAdapter.java:1881)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at com.eleybourn.bookcatalogue.utils.StorageUtils.sendDebugInfo(StorageUtils.java:318)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at com.eleybourn.bookcatalogue.Help$3.onClick(Help.java:93)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at android.view.View.performClick(View.java:7259)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at android.view.View.performClickInternal(View.java:7236)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at android.view.View.access$3600(View.java:801)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at android.view.View$PerformClick.run(View.java:27892)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at android.os.Handler.handleCallback(Handler.java:883)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at android.os.Looper.loop(Looper.java:214)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at java.lang.reflect.Method.invoke(Native Method)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
04-03 14:59:46.534 18021 18021 E BC Logger: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at libcore.io.Linux.open(Native Method)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
04-03 14:59:46.534 18021 18021 E BC Logger: 	at libcore.io.IoBridge.open(IoBridge.java:482)
04-03 14:59:46.534 18021 18021 E BC Logger: 	... 17 more
04-03 14:59:46.562 18021 18021 E BC Logger: An Exception Occured @ 2021-04-03 14:59:46
04-03 14:59:46.562 18021 18021 E BC Logger: In Phone GT-I9505 (29) 
04-03 14:59:46.562 18021 18021 E BC Logger: 
04-03 14:59:46.562 18021 18021 E BC Logger: java.lang.NullPointerException: Attempt to get length of null array
04-03 14:59:46.562 18021 18021 E BC Logger: 	at com.eleybourn.bookcatalogue.utils.StorageUtils.sendDebugInfo(StorageUtils.java:394)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at com.eleybourn.bookcatalogue.Help$3.onClick(Help.java:93)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at android.view.View.performClick(View.java:7259)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at android.view.View.performClickInternal(View.java:7236)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at android.view.View.access$3600(View.java:801)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at android.view.View$PerformClick.run(View.java:27892)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at android.os.Handler.handleCallback(Handler.java:883)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at android.os.Looper.loop(Looper.java:214)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at java.lang.reflect.Method.invoke(Native Method)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-03 14:59:46.562 18021 18021 E BC Logger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
...
```

A small transcript of an `adb shell` session:
```sh
jflte:/storage/emulated/0/bookCatalogue $ ls -lrt
...
-rw-rw---- 1 root sdcard_rw    9937 2021-02-20 20:07 tmp_GB.jpg
-rw-rw---- 1 root sdcard_rw    9937 2021-02-20 20:07 9e8d1f27d6df3fb19c95c6a039dba297.jpg
-rw-rw---- 1 root sdcard_rw     599 2021-02-20 20:07 3db78fdeb4065af332a30f87da6c1a92.jpg
-rw-rw---- 1 root sdcard_rw       0 2021-03-05 11:45 error.log
-rw-rw---- 1 root sdcard_rw    4573 2021-03-05 11:45 bee33e1028a493be907aaa4d324f0668.jpg
```

Strange thing: in android permissions screen for book catalog, I have twice "Storage". Not sure if it’s the normal behaviour.
Reading this [page](https://developer.android.com/training/data-storage/shared/media#scoped_storage_enabled), maybe, the manifest of BC should be adapted?

Best regards

**Comment by ttamttam** [comment]
Hurra! I can now again use Book Catalogue as expected.

How did I?

From the applications management menu of Android, I clicked on the "Storage space and cache" menu (**warning:** all menus I’m showing here are personal translation of the french menus). The storage space in use was "SD-card". I chose to "Modify" this for "shared internal storage space".

**Comment by Grunthos** [comment]
Glad you managed to solve this; the latest version (6.0.2) no longer uses the SD card and should be more able to export/import from arbitrary locations.
