### ISSUE TITLE
Can't install on Pixel 7, Android 13

### ISSUE THREAD

**Issue by david-bakin** [eleybourn/Book-Catalogue#890]
Been using Book Catalogue for quite a few years, on my Note 8 and a predecessor phone too.  Have ~1750 books cataloged and still adding to it weekly.  But it won't install on a Pixel 7.  (Can't really even find it in the Play Store any more - but it shows up in "My Apps" with the Pixel 7 greyed out.)

Wish it would receive an update, even if to do nothing more than get it working with Android 13/Pixel 7/whatever the issue is.

Though a few months ago search via Amazon slowed down tremendously, so fixing that would be nice too.

(If you're no longer interested in maintaining this app that's understandable, it's had a good long run, and thank you!)

**Comment by Grunthos** [comment]
Hi,

There  is an update on the way; it should be available in the next 24 hours.

Thanks,

Philip Warner



-

From: David Bakin
Sent: Monday, 19 June 2023 8:20 AM
To: eleybourn/Book-Catalogue
Cc: Subscribed
Subject: [eleybourn/Book-Catalogue] Can't install on Pixel 7, Android 13(Issue #890)

Been using Book Catalogue for quite a few years, on my Note 8 and a predecessor phone too. Have ~1750 books cataloged and still adding to it weekly. But it won't install on a Pixel 7. (Can't really even find it in the Play Store any more - but it shows up in "My Apps" with the Pixel 7 greyed out.)
Wish it would receive an update, even if to do nothing more than get it working with Android 13/Pixel 7/whatever the issue is.
Though a few months ago search via Amazon slowed down tremendously, so fixing that would be nice too.
(If you're no longer interested in maintaining this app that's understandable, it's had a good long run, and thank you!)

**Comment by Grunthos** [comment]
This update is in staged release at the moment.

**Comment by Grunthos** [comment]
This is now released
